# -*- coding: utf-8 -*-
"""Desenvolvimento de Sistemas II - 2 ° Exercício de Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UbbayKBMReIUWdZM2ylbv6lHZ-2ZrYXc
"""

dic_cliente = {}

def cadastro_novo(lista, cpf, nome, endereco, telefone, data_nascimento):
  lista.append(cpf)
  lista.append(nome)
  lista.append(endereco)
  lista.append(telefone)
  lista.append(data_nascimento)

def arrumacao_dic(dicionario, lista):
  chave = lista[0]
  dicionario [chave] = lista[1:]

def menu():
  cadastro = []
  print(40 * "=")
  print("\tCadastro de clientes")
  print(40 * "=")
  cpf = input("CPF: ")
  nome = input("Nome: ")
  endereco = input("Endereço: ")
  telefone = input("Telefone: ")
  dataNascimento = input("Data de Nascimento: ")
  
  cadastro_novo(cadastro, cpf, nome, endereco, telefone, dataNascimento)
  arrumacao_dic(dic_cliente, cadastro)

def relatorio():
  print("\n")
  print(40 * "=")
  print("\t RELATÓRIO DE CLIENTES")
  print(40 * "=")
  list = dic_cliente.keys()
  quant = 00
  for chave in list:
    quant += 1
    print("{:02d} CPF: {}".format(quant, chave))
    print("Nome: {}".format(dic_cliente[chave][0]))
    print("Endereço: {}".format(dic_cliente[chave][1]))
    print("Telefone: {}".format(dic_cliente[chave][2]))
    print("Data de Nascimento: {}\n".format(dic_cliente[chave][3]))

while True:
  menu()
  mais_cadastro = input("\nDeseja cadastrar outro Cliente: S/N: ")
  if (mais_cadastro == "N"):
    break
relatorio()

